version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./app
    volumes: ['./app:/app']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    volumes:
        - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        - "cluster.name=elasticsearch"
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"
    networks:
        - apinetwork
    healthcheck:
        test: "curl http://elasticsearch:9200"
        interval: "1s"
        timeout: "3s"
        retries: 60

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass password
    ports:
        - "6379:6379"
    volumes:
        - /tmp/redis-data:/var/lib/redis
    environment:
        - REDIS_REPLICATION_MODE=master
    networks:
        - apinetwork

networks:
  apinetwork:
